name = "convergence-games"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "GAME_STATE"
id = "151bf2db12704b7ca1d819c6374ba8de"
preview_id = "151bf2db12704b7ca1d819c6374ba8de"